type Character {
  uid: ID
  name: String
  game: String
  stats: [Stat] @relation
}

type Stat {
  character: Character
  name: String
  die: String
  bonus: Int
  skills: [Skill] @relation
}

type Skill {
  name: String
  die: String
  bonus: Int
  stat: Stat
}

type Query {
  charactersByGame(uid: ID!, game: String): [Character]
}
