name: Lint HTML
on: [pull_request]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install npm dependencies
        run: npm ci
      - name: build the site
        run: npm run build
      - name: lint html
        run: npm run lint:html
